version: "3.2"
services:
  php7:
    container_name: php7
    image: php:apache-buster
    # network_mode: host
    ports:
      - 7000:80
    volumes:
      - ./apache2/000-default.conf/:/etc/apache2/sites-available/000-default.conf
      - ./volume/:/var/www:rw
    working_dir: /var/www
    environment:
      TZ: Asia/Tokyo

  reverse-proxy:
    image: nginx
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80