version: "3.2"
services:
  web01:
    container_name: px-apache1
    image: www-data:apache-buster
    ports:
      - 7001:80
    volumes:
      - ./apache2/000-default.conf/:/etc/apache2/sites-available/000-default.conf:ro
      - ./volume/apache1/:/var/www:rw
    working_dir: /var/www
    working_dir: /var/www
    environment:
      TZ: Asia/Tokyo
  web02:
    container_name: px-apache2
    image: www-data:apache-buster
    ports:
      - 7002:80
    volumes:
      - ./apache2/000-default.conf/:/etc/apache2/sites-available/000-default.conf:ro
      - ./volume/apache2/:/var/www:rw
    working_dir: /var/www
    environment:
      TZ: Asia/Tokyo

  reverse-proxy:
    container_name: px-nginx
    image: nginx
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80